include:
  remote: 'https://github.com/git-developer/solarview-base/raw/v1.6.0/.gitlab-ci.yml'

variables:
  DOCKERFILE_URL: 'https://github.com/git-developer/solarview-base/raw/v1.6.0/Dockerfile'
  BUILD_ARGS: 'APP_NAME=sunspec-fb RUNTIME_BASE_IMAGE=debian:testing-slim'
  IMAGE_TITLE: 'SolarView Sunspec-Proxy'
  UPDATE_CHECK_URLS: 'http://www.solarview.info/downloads/sunspec-fb.zip'
